name: pipeline de qa

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ativando a pipeline de qa
